name: Miri Unit Tests

on:
  workflow_call:

jobs:
  test:
    name: Miri Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1
      - name: Install Rust toolchain with Miri
        uses: dtolnay/rust-toolchain@e2a55d2ffb04f378e9626c28d38b36d230d1e12f # v1
        with:
          components: miri, rust-src
          toolchain: nightly
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3
        with:
          repo-token: ${{ github.token }}
      - name: Cache cargo registry, index, and targets
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          prefix-key: "cargo-miri"
      - name: Download Cargo.lock
        uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8
        with:
          name: lockfile
          path: .
      - name: Run Miri tests
        run: |
          RUST_BACKTRACE=1 \
          MIRIFLAGS="-Zmiri-backtrace=full" \
          cargo +nightly miri test --all --locked --all-features --verbose
        shell: bash
